frameworkVersion: ^2.15.0

service: gTransX-py

plugins:
  - serverless-offline
  - serverless-python-requirements

custom:
  stage: "${opt:stage, env:SLS_STAGE, 'dev'}"
  log_level: "${env:LOG_LEVEL, 'INFO'}"

  pythonRequirements:
    dockerizePip: false
    # pythonBin: C:\Users\yaidelg\AppData\Local\Programs\Python\Python38\python.exe

provider:
  name: aws
  runtime: python3.8
  stage: ${self:custom.stage}
  environment:
    LOG_LEVEL: ${self:custom.log_level}
  stackTags:
    x-service: ${self:service}
    x-stack: ${self:service}-${self:provider.stage}
  apiGateway:
    shouldStartNameWithService: true

functions:
  translate:
    handler: handlers/translate.handler
    description: ""
    memorySize: 128
    timeout: 60
    events:
      - http:
          path: /translate
          method: post
          cors: true
          integration: lambda
